language: java

jdk:
  - openjdk8

script: mvn clean test

notifications:
  email:
    recipients:
      - surya_uppuluri@outlook.com
      - usuryasatyakumar@gmail.com
    on_failure: always
    on_success: always

